name: Build e Testes

on:
  push:
    branches:
      - feature/**
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Permissão de execução para gradlew
        run: chmod +x gradlew

      - name: Build com Gradle
        run: ./gradlew build --no-daemon

      - name: Executar Testes com Cobertura
        run: ./gradlew test jacocoTestReport --no-daemon

      - name: Exibir Cobertura Total
        run: |
          echo "Extraindo cobertura de testes..."
          # Extrai a linha referente à cobertura de linhas do relatório XML
          total_line=$(grep "<counter type=\"LINE\"" build/reports/jacoco/test/jacocoTestReport.xml)
          missed=$(echo "$total_line" | sed -n 's/.*missed="\([0-9]*\)".*/\1/p')
          covered=$(echo "$total_line" | sed -n 's/.*covered="\([0-9]*\)".*/\1/p')
          total=$((missed + covered))
          # Calcula a porcentagem de cobertura
          coverage=$(awk "BEGIN {printf \"%.2f\", ($covered/$total)*100}")
          echo "Cobertura total de linhas: $coverage%"
