name: Build e Testes

on:
  push:
    branches:
      - feature/**
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Permissão de execução para gradlew
        run: chmod +x gradlew

      - name: Build com Gradle
        run: ./gradlew build --no-daemon
